repos:
  backports-3.20:
    main_ref: "master"
    build_args:
      ALPINE_VERSION: "3.20"
    envs:
      JOBS: 4
      PURGE_OBSOLETE: "yes"
      STACK_PROTECTOR: "on"
    args: ["v3.20/backports"]
    repo_path: "/home/builder/packages/backports"
    cache_path: "/cache"
    sign_key_path: "/home/builder/.abuild/builder@alpine-ros-experimental.rsa"
    upload:
      - remote: "main"
        paths: ["v3.20/backports"]
        archive_paths: ["archives/v3.20/backports"]
      - remote: "mirror"
        paths: ["v3.20/backports"]
        archive_paths: ["archives/v3.20/backports"]
  noetic-3.20:
    main_ref: "master"
    deps:
      backports-3.20: /home/builder/deps/backports
    build_args:
      ALPINE_VERSION: "3.20"
      ROS_DISTRO: "noetic"
    envs:
      JOBS: 4
      PURGE_OBSOLETE: "yes"
      STACK_PROTECTOR: "on"
    args: ["v3.20/ros/noetic"]
    repo_path: "/home/builder/packages/noetic"
    cache_path: "/cache"
    sign_key_path: "/home/builder/.abuild/builder@alpine-ros-experimental.rsa"
    upload:
      - remote: "main"
        paths: ["v3.20/ros/noetic"]
        archive_paths: ["archives/v3.20/ros/noetic"]
      - remote: "mirror"
        paths: ["v3.20/ros/noetic"]
        archive_paths: ["archives/v3.20/ros/noetic"]
  jazzy-3.20:
    main_ref: "master"
    deps:
      backports-3.20: /home/builder/deps/backports
    build_args:
      ALPINE_VERSION: "3.20"
      ROS_DISTRO: "jazzy"
    envs:
      JOBS: 4
      PURGE_OBSOLETE: "yes"
      STACK_PROTECTOR: "on"
    args: ["v3.20/ros/jazzy"]
    repo_path: "/home/builder/packages/jazzy"
    cache_path: "/cache"
    sign_key_path: "/home/builder/.abuild/builder@alpine-ros-experimental.rsa"
    upload:
      - remote: "main"
        paths: ["v3.20/ros/jazzy"]
        archive_paths: ["archives/v3.20/ros/jazzy"]
      - remote: "mirror"
        paths: ["v3.20/ros/jazzy"]
        archive_paths: ["archives/v3.20/ros/jazzy"]
  backports-3.17:
    main_ref: "master"
    build_args:
      ALPINE_VERSION: "3.17"
    envs:
      JOBS: 4
      PURGE_OBSOLETE: "yes"
      STACK_PROTECTOR: "on"
    args: ["v3.17/backports"]
    repo_path: "/home/builder/packages/backports"
    cache_path: "/cache"
    sign_key_path: "/home/builder/.abuild/builder@alpine-ros-experimental.rsa"
    upload:
      - remote: "main"
        paths: ["v3.17/backports"]
        archive_paths: ["archives/v3.17/backports"]
      - remote: "mirror"
        paths: ["v3.17/backports"]
        archive_paths: ["archives/v3.17/backports"]
  noetic-3.17:
    main_ref: "master"
    deps:
      backports-3.17: /home/builder/deps/backports
    build_args:
      ALPINE_VERSION: "3.17"
      ROS_DISTRO: "noetic"
    envs:
      JOBS: 4
      PURGE_OBSOLETE: "yes"
      STACK_PROTECTOR: "on"
    args: ["v3.17/ros/noetic"]
    repo_path: "/home/builder/packages/noetic"
    cache_path: "/cache"
    sign_key_path: "/home/builder/.abuild/builder@alpine-ros-experimental.rsa"
    upload:
      - remote: "main"
        paths: ["v3.17/ros/noetic"]
        archive_paths: ["archives/v3.17/ros/noetic"]
      - remote: "mirror"
        paths: ["v3.17/ros/noetic"]
        archive_paths: ["archives/v3.17/ros/noetic"]
  humble-3.17:
    main_ref: "master"
    deps:
      backports-3.17: /home/builder/deps/backports
    build_args:
      ALPINE_VERSION: "3.17"
      ROS_DISTRO: "humble"
    envs:
      JOBS: 4
      PURGE_OBSOLETE: "yes"
      STACK_PROTECTOR: "on"
    args: ["v3.17/ros/humble"]
    repo_path: "/home/builder/packages/humble"
    cache_path: "/cache"
    sign_key_path: "/home/builder/.abuild/builder@alpine-ros-experimental.rsa"
    upload:
      - remote: "main"
        paths: ["v3.17/ros/humble"]
        archive_paths: ["archives/v3.17/ros/humble"]
      - remote: "mirror"
        paths: ["v3.17/ros/humble"]
        archive_paths: ["archives/v3.17/ros/humble"]
