repos:
  backports-alpine3.14:
    main_ref: "master"
    build_args:
      ALPINE_VERSION: "3.14"
    envs:
      JOBS: 4
      PURGE_OBSOLETE: "yes"
      STACK_PROTECTOR: "on"
    args: ["backports"]
    repo_path: "/home/builder/packages/backports"
    cache_path: "/cache"
    sign_key_path: "/home/builder/.abuild/builder@alpine-ros-experimental.rsa"
    upload:
      - remote: "main"
        paths: ["v3.14/backports"]
        archive_paths: ["archives/v3.14/backports"]
      - remote: "mirror"
        paths: ["v3.14/backports"]
        archive_paths: ["archives/v3.14/backports"]
  noetic-alpine3.14:
    main_ref: "master"
    deps:
      backports-alpine3.14: /home/builder/packages.ro/backports
    build_args:
      ALPINE_VERSION: "3.14"
      ROS_DISTRO: "noetic"
    envs:
      JOBS: 4
      PURGE_OBSOLETE: "yes"
      STACK_PROTECTOR: "on"
    args: ["ros/noetic.v3.14"]
    repo_path: "/home/builder/packages/ros/noetic.v3.14"
    cache_path: "/cache"
    sign_key_path: "/home/builder/.abuild/builder@alpine-ros-experimental.rsa"
    upload:
      - remote: "main"
        paths: ["v3.14/ros/noetic"]
        archive_paths: ["archives/v3.14/ros/noetic"]
      - remote: "mirror"
        paths: ["v3.14/ros/noetic"]
        archive_paths: ["archives/v3.14/ros/noetic"]
  backports-alpine3.17:
    main_ref: "master"
    build_args:
      ALPINE_VERSION: "3.17"
    envs:
      JOBS: 4
      PURGE_OBSOLETE: "yes"
      STACK_PROTECTOR: "on"
    args: ["backports"]
    repo_path: "/home/builder/packages/backports"
    cache_path: "/cache"
    sign_key_path: "/home/builder/.abuild/builder@alpine-ros-experimental.rsa"
    upload:
      - remote: "main"
        paths: ["v3.17/backports"]
        archive_paths: ["archives/v3.17/backports"]
      - remote: "mirror"
        paths: ["v3.17/backports"]
        archive_paths: ["archives/v3.17/backports"]
  noetic-alpine3.17:
    main_ref: "master"
    deps:
      backports-alpine3.17: /home/builder/packages.ro/backports
    build_args:
      ALPINE_VERSION: "3.17"
      ROS_DISTRO: "noetic"
    envs:
      JOBS: 4
      PURGE_OBSOLETE: "yes"
      STACK_PROTECTOR: "on"
    args: ["ros/noetic.v3.17"]
    repo_path: "/home/builder/packages/ros/noetic.v3.17"
    cache_path: "/cache"
    sign_key_path: "/home/builder/.abuild/builder@alpine-ros-experimental.rsa"
    upload:
      - remote: "main"
        paths: ["v3.17/ros/noetic"]
        archive_paths: ["archives/v3.17/ros/noetic"]
      - remote: "mirror"
        paths: ["v3.17/ros/noetic"]
        archive_paths: ["archives/v3.17/ros/noetic"]
