repos:
  backports-3.14:
    main_ref: "master"
    build_args:
      ALPINE_VERSION: "3.14"
    envs:
      JOBS: 4
      PURGE_OBSOLETE: "yes"
      STACK_PROTECTOR: "on"
    args: ["backports"]
    repo_path: "/home/builder/packages/backports"
    cache_path: "/cache"
    sign_key_path: "/home/builder/.abuild/builder@alpine-ros-experimental.rsa"
    upload:
      - remote: "main"
        paths: ["v3.14/backports"]
        archive_paths: ["archives/v3.14/backports"]
      - remote: "mirror"
        paths: ["v3.14/backports"]
        archive_paths: ["archives/v3.14/backports"]
  noetic-3.14:
    main_ref: "master"
    deps:
      backports-3.14: /home/builder/deps/backports
    build_args:
      ALPINE_VERSION: "3.14"
      ROS_DISTRO: "noetic"
    envs:
      JOBS: 4
      PURGE_OBSOLETE: "yes"
      STACK_PROTECTOR: "on"
    args: ["ros/noetic.v3.14"]
    repo_path: "/home/builder/packages/noetic"
    cache_path: "/cache"
    sign_key_path: "/home/builder/.abuild/builder@alpine-ros-experimental.rsa"
    upload:
      - remote: "main"
        paths: ["v3.14/ros/noetic"]
        archive_paths: ["archives/v3.14/ros/noetic"]
      - remote: "mirror"
        paths: ["v3.14/ros/noetic"]
        archive_paths: ["archives/v3.14/ros/noetic"]
  backports-3.17:
    main_ref: "master"
    build_args:
      ALPINE_VERSION: "3.17"
    envs:
      JOBS: 4
      PURGE_OBSOLETE: "yes"
      STACK_PROTECTOR: "on"
    args: ["backports"]
    repo_path: "/home/builder/packages/backports"
    cache_path: "/cache"
    sign_key_path: "/home/builder/.abuild/builder@alpine-ros-experimental.rsa"
    upload:
      - remote: "main"
        paths: ["v3.17/backports"]
        archive_paths: ["archives/v3.17/backports"]
      - remote: "mirror"
        paths: ["v3.17/backports"]
        archive_paths: ["archives/v3.17/backports"]
  noetic-3.17:
    main_ref: "master"
    deps:
      backports-3.17: /home/builder/deps/backports
    build_args:
      ALPINE_VERSION: "3.17"
      ROS_DISTRO: "noetic"
    envs:
      JOBS: 4
      PURGE_OBSOLETE: "yes"
      STACK_PROTECTOR: "on"
    args: ["ros/noetic.v3.17"]
    repo_path: "/home/builder/packages/noetic"
    cache_path: "/cache"
    sign_key_path: "/home/builder/.abuild/builder@alpine-ros-experimental.rsa"
    upload:
      - remote: "main"
        paths: ["v3.17/ros/noetic"]
        archive_paths: ["archives/v3.17/ros/noetic"]
      - remote: "mirror"
        paths: ["v3.17/ros/noetic"]
        archive_paths: ["archives/v3.17/ros/noetic"]
  humble-3.17:
    main_ref: "master"
    deps:
      backports-3.17: /home/builder/deps/backports
    build_args:
      ALPINE_VERSION: "3.17"
      ROS_DISTRO: "humble"
    envs:
      JOBS: 4
      PURGE_OBSOLETE: "yes"
      STACK_PROTECTOR: "on"
    args: ["ros/humble.v3.17"]
    repo_path: "/home/builder/packages/humble"
    cache_path: "/cache"
    sign_key_path: "/home/builder/.abuild/builder@alpine-ros-experimental.rsa"
    upload:
      - remote: "main"
        paths: ["v3.17/ros/humble"]
        archive_paths: ["archives/v3.17/ros/humble"]
      - remote: "mirror"
        paths: ["v3.17/ros/humble"]
        archive_paths: ["archives/v3.17/ros/humble"]
