#!/bin/sh

set -u

GCC_ICE_RETRY_NUM=${GCC_ICE_RETRY_NUM:-5}

compiler=$(basename $0)

for i in $(seq ${GCC_ICE_RETRY_NUM}); do
  /usr/lib/ccache/bin/${compiler} -pass-exit-codes $@
  exit_code=$?
  case ${exit_code} in
    4)
      echo "gcc internal compiler error is detected: retrying (${i})" >&2
      continue
      ;;
    0)
      exit 0
      ;;
    *)
      echo "gcc failed with exit code ${exit_code}" >&2
      exit ${exit_code}
      ;;
  esac
done
