#!/bin/sh

set -u

GCC_ICE_RETRY_NUM=${GCC_ICE_RETRY_NUM:-5}

compiler=$(basename $0)

for i in $(seq ${GCC_ICE_RETRY_NUM}); do
  /usr/lib/ccache/bin/${compiler} $@
  exit_code=$?
  case ${exit_code} in
    4)
      echo "gcc internal compiler error is detected: retrying (${i})"
      continue
      ;;
    *)
      exit ${exit_code}
      ;;
  esac
done
